//http://www.rodrynia.pl/index.php/przysowia-o-pogodzie?showall=1

var przyslowia=[];

przyslowia[1]=[
'Bój się w styczniu wiosny, bo marzec zazdrosny',
'Jeżeli pszczoła w styczniu z ula wylatuje, rzadko pomyślny rok nam obiecuje',
'Na stycznie i lute trzeba mieć konie kute',
'Styczeń pogodny wróży rok płodny',
'Gdy w styczniu deszcz leje, złe robi nadzieje',
'Kiedy styczeń najostrzejszy, wtedy roczek najpłodniejszy'
];

przyslowia[2]=[
'Czasem luty ostro kuty, czasem w luty same pluty',
'Czasem luty się zlituje, że człek niby wiosnę czuje; ale czasem tak się zżyma, że człek prawie nie wytrzyma',
'Gdy ciepło w lutym, zimno w marcu bywa, długo trwa zima, to jest niewątpliwa',
'Jak po lutym marzec, to po maju czerwiec',
'Jeśli ci jeszcze nie dokuczył luty, to pal dobrze w kominie i miej kożuch suty',
'Spyta cię luty: masz-li buty?',
'W lutym gdy zagrzmi od wschodniego boku, burze i wiatry walne są w tym roku',
'Idzie luty, podkuj buty',
'Kiedy luty, obuj buty',
'Kiedy luty puści, to marzec wypiecze',
'Luty w lód okuty',
'Spyta cię luty: masz-li buty?',
'Św. Walenty odmrozi ci pięty',
'Gdy mróz w lutym ostro trzyma, tedy jest niedługa zima',
'Kiedy luty puści, to marzec wypiecze',
'W lutym wody wiele – w lecie głodne nawet cielę',
'Kiedy luty schodzi, człek po wodzie brodzi',
'W lutym gdy zagrzmi od wschodniego boku, burze i wiatry walne są w tym roku',
'Czasem sie Luty zlituje że człek niby wiosnę czuje ale czasem sie tak zżyma że człek prawie nie wytrzyma.',
'Gdy na Gromnice roztaje, rzadkie będą urodzaje.',
'Gdy w Gromnice pięknie wszędzie, tedy dobra wiosna będzie.',
'Gdy w Gromniczną jest ładnie, dużo śniegu jeszcze spadnie.',
'Gdy w Gromnicę z dachów ciecze, zima jeszcze się przewlecze.',
'Gromniczna pogodna, będzie jesień dorodna.',
'Kiedy Gromniczna zimę traci, to Święty Maciej (24.02) ją wzbogaci.',
'Kiedy w Gromniczną gęś chodzi po wodzie, to będzie na Wielkanoc chodzić po lodzie.',
'Na Gromnicę - masz zimy połowicę.',
'Jak słońce jasno Świeci na Gromnice, to przyjdą wielkie mrozy i śnieżyce.',
'Jaka Gromniczna bracie, taki Święty Maciej (24.02)',
'Gdy jasne słońce w dzień gromniczny będzie, więcej niż przedtem śniegu spadnie wszędzie.',
'Gromnice w śniegu, wiosna jest w biegu, lecz gdy pogoda, dla wiosny zawoda.',
'Jak na Matkę Gromniczną, tak na Święty Józef (19.03).',
'Jak suche i jasne Gromnice, przyjdą jeszcze śnieżyce.',
'Jasna Gromnica - zła orędownica.',
'Kiedy na Gromniczną mróz, zładuj sanie, szykuj wóz.',
'Maria pogodna, będzie jesień dorodna.',
'Na Gromniczną Pan Bóg daje, czasem mróz, czasem roztaje.',
'Na Oczyszczenie Marii Panny, zbliża się koniec sanny.',
'Pamiętaj, że Gromnica, to już zimy połowica, ale żadna też nowina, gdy dopiero się zaczyna.',
];


przyslowia[3]=[
'Marzec czy słoneczny, czy płaczliwy, listopada obraz żywy',
'W marcu jak w garncu',
'Na wiosnę ceber deszczu, łyżka błota; na jesieni łyżka deszczu, ceber błota',
'A po lutym marzec spieszy, koniec zimy wszystkich cieszy.',
'Na Świętego Albina rzadka u ludzi mina, bo post się zaczyna.',
'Chłodny marzec, ciepły maj, będzie zboże jako gaj.',
'Czasem i w marcu, zetnie wodę w garncu.',
'Gdy marzec mglisty, w lecie czas dżdżysty.',
'Gdy marzec suchy, kwiecień nagradza, bo deszcze sprowadza.',
'Gdy w marcu grzmi, w maju śniegiem cmi.',
'Gdy w marcu topnieje, to na wiosnę mróz bieleje.',
'Kto sieje groch w marcu, gotuje go w garncu, a kto w maju, ten w jaju',
'Na Świętą Kondę wyrzuc już bondę (zimowe okrycie).',
'Deszcze marcowe zbożu niezdrowe.',
'Gdy marzec suchy, kwiecień nagradza, bo deszcze sprowadza.',
'Gdy w marcu grzmi, w maju śniegiem ćmi.',
'Gdy w marcu topnieje, to na wiosnę mróz bieleje',
'Dzień Świętego Kazimierza resztki zimy uśmierza.',
'Jeżeli na Świętego Kazimierza pogoda, to na ziemniaki woda (na wykopki).',
'Na Świętego Kazimierza pełno już młodego zwierza.',
'Na Świętego Kazimierza wyjdzie skowronek spod pierza.',
'Święty Kazimierz groch dmie.',
'W dzień Świętego Kazimierza zima do morza zmierza.',
'Jak w Kazimierza pochmurno, o jarzynę nietrudno.',
'Na Kazimierza dzień się z nocą przymierza',
'Jak tłuste zapusty, to dom może być pusty.',
'Jakie zapusty, taka Wielkanoc.',
'Jeśli zapusty pogodne bywają, Świąt wielkanocnych tak się spodziewają.',
'Ostatni wtorek wskazuje, jaka pogoda w poście panuje.',
'Kiedy pada w ostatni wtorek, to ze lnem uciekaj w dołek.',
'Zapust smutny, post wesoły, będziesz człeku, cały rok goły',
'Gdy w Popielec pogoda, wiosna będzie sucha; gdy deszcz będzie mokra; a jeżeli zimno, będzie zimna.',
'Po deszczu środa popielcowa i wiosna deszczowa.',
'Gdy w Popielec pogoda służy, suchą wiosnę wróży.',
'Jeśli po deszczu środa popielcowa, to cała wiosna bywa deszczowa.',
'Jak się we środę zapustną powietrze ma, tak się przez cały post trzyma.',
'W środę popielcową pogoda jaka, przez wszystek post taka',
'Gdy w marcu niebo od południa ryknie, rok wszego dobra z tego wyniknie.',
'W marcu, gdy są grzmoty, urośnie zboże ponad płoty.',
'Gdy w marcu deszcz pada, wtedy rolnik biada, gdy słonko jaśnieje, to rolnik się śmieje.',
'Marzec zimny i słoneczny, plon zaręcza dostateczny.',
'Ile mgieł w marcu, tyle deszczów w czerwcu',
'Kiedy w marcu plucha, to w maju posucha.',
'W marcu mgły bywają, w lecie burze przeszkadzają.',
'Co marzec wypiecze, to kwiecień wyciecze.',
'Nie ma w marcu wody, nie ma w kwietniu trawy.',
'W marcu kto siać nie zaczyna, dobra swego zapomina',
'Dzień kobiet !! Wszystkim paniom miłego dnia',
'Gdy Franciszka z wichrem po polu hasa, może sypnąć śniegiem powyżej pasa',
'Od Cypriana aż do Jana (Kapistrana 27.03), gdy pogoda zakichana, to od Jana do Jerzego (23.04) ciągle jeszcze nic nowego, a gdy Jerzy się rozśmieje (rozpogodzi), to za kilka dni znów leje.',
'Czterdziestu Męczenników jakich, czterdzieści dni takich.',
'Gdy mróz w marcu dnia dziesiątego, jeszcze czterdzieści dni mrozu takiego.',
'Męczennicy, gdy mróz noszą, czterdzieści dni mrozu głoszą.',
'Męczennicy jeśli psocą, będzie dżdżysto Wielką Nocą, a gdy kropla dżdżu nie spadnie, przez sześć niedziel będzie ładnie.',
'Kiedy w marcu deszczu wiele, nieurodzaj zboża ściele.',
'Marzec zielony, niedobre plon',
'A po marcu, co mgłą raczy, tyleż lato się napłacze.',
'Ruszaj w marcu w pole, by po trochu rzucic w ziemię owsa, grochu.',
'Gdy marzec deszczowy, suche lato rodzi i zasiewom szkodzi.',
'Suchy marzec, mokry maj, będzie żytko jako (niby) gaj.',
'W marcu słońce grzeje, czasem śnieżek sieje.',
'Suchy marzec kwiecień nagradza, bo na pola deszcze sprowadza.',
'To, co marzec sobie marzy, to jest sęk dla gospodarzy.',
'W marcu, choć słota, rzucaj zboże do błota.',
'Marzec, co z deszczem chadza, mokry czerwiec sprowadza',
'Na Św. Grzegorza idzie zima do morza.',
'Groch, Święty Grzegorz zasiewa, soczewicę Jakub miewa.',
'I na lądzie, i na morzu, wszędzie bieda, mój Grzegorzu.',
'Jeszcze Grześ gdzieś, a już mu kaszę studzą.',
'Po Świętym Grzegorzu nie paś bydła na zbożu.',
'Gust kobiety, łaska pańska i marcowa pogoda zawsze niestałe.',
'Nie siejesz grochu w marcu,, nie masz go w garncu.',
'Kiedy starzec chory w marcu, będzie zdrów, lecz gdy baba w maju słaba, pacierz zmów.',
'Marzec, czy słoneczny, czy płaczliwy, listopada obraz żywy .',
'Marzec suchy; kwiecień, gdy w deszcz bogaty bywa; maj zaś chłodny ? w urodzaj taki rok opływa.',
'Śnieg marcowy owocom niezdrowy.',
'W marcu mgły, powódz za sto dni.',
'Ile razy marzec mgłą uraczy, tyle niepogody w lecie znaczy',
'Piętnastego marca słonko grzeje i starca.',
'Gdy się trawa zieleni w marcu, to jej nie ma w maju.',
'Co marzec wypiecze, to kwiecień wysiecze.',
'Suchy marzec, mokry kwiecień, maj chłodny ? rok niegłodny',
'Hilary zapowiada, jaka pogoda w Wielkanoc przypada.',
'Marzec - figlarzec, przeplata, trochę zimy, trochę lata.',
'Marzec uparty stroi z pługiem żarty.',
'Każdy gospodarz zasiewa pierwszy groch na marca, aby też próżnego nie miał na ognicku garnca.',
'Gabrielu, przyjacielu, nie mroz nas, łysych jest wielu.',
'Gdy na Gertrudy zjawią się bociany, to wiosna już rychło nastanie.',
'Święta Gertruda ? zaprzęgaj woły do pługa.',
'Ogrodniku, Św. Gertruda gdy słońcem błyśnie zrobi cuda oczywiście.',
'W dzień Gertrudy, jeśli mróz u nas, przez czterdzieści dni zimowy czas.',
'Od Trzech Króli (06.01) będą mrozy do Gietruli.',
'Na Św. Edwarda zimy pogarda.',
'Po marcu, co mgłą raczy, tyleż lato się zapłacze.',
'Po marcu grzmiącym, maj śniegiem ćmiący.',
'Suchy marzec, mokry maj czyni gumno jako gaj.',
'Jak na Świętego Józefa chmurki, to sadź ziemniaki gdzie górki, a jak pogoda, to sadź gdzie woda.',
'Gdy na Święty Józef bociek przybędzie, to już śniegu nie będzie.',
'Na Świętego Józefa pięknie, zima prędko pęknie.',
'Na Święty Józek czasem śniegu, a czasem trawy wózek.',
'Przyjdzie Święty Józef z pomocą, porówna dzień z nocą.',
'Święty Józef kiwnie brodą, idzie zima na dół z wodą.',
'Święty Józef pogodny, będzie roczek wodny.',
'W Józefa z zimy się śmiej i na grządce kapustę siej.',
'Gdy w Ruprechta jasno, ponoć w czerwcu krasno.',
'Od dnia dwudziestego marca zagrzewa słońce nawet starca.',
'Gdy suchy marzec, a maj mokry bywa, żyznego roku oracz się spodziewa.',
'Jak przylecą żurawie, można bydło paść na trawie',
'Pierwszy dzień wiosny !!',
'Jak po Benedykcie ciepło, to i w lecie będzie piekło.',
'Benedykt groch w polu sieje, Wojciech (23.04) do owsa się śmieje,',
'Stanisław (08.05)len ma w pamięci, Filip (01.05) do tatarki nęci.',
'Benedykta Bożą mocą, dzionek już się równa z nocą.',
'Gdy gęś dzika w marcu przybywa, ciepła wiosna bywa.',
'Jeżeli w pierwszy dzień po przesileniu marcowym burza się zdarzy, zimy już nie będzie.',
'W marcu, kto siać nie zaczyna, biednyć to gospodarzyna.',
'Zima, gdy mrozem nie wygodzi, marzec z kwietniem wraz wychłodzi.',
'Posuchy marcowe wynagrodzą deszcze kwietniowe',
'Czego nie dokaże marzec, dokaże kwiecień.',
'W marcu, kto siać nie zaczyna, swego dobra zapomina, spiesz więc w pole, by po trochu, rzucić w ziemię owsa, grochu.',
'Marca obraz wierny, to miesiąc październy.',
'Na Świętego Szymona nie wdziewaj już kaftana.',
'Zwiastowanie Najświętszej Marii Panny, Matki Boskiej Kwietnej',
'W dni krzyżowe męka boża, wstrzymaj się od siewu zboża.',
'Jakie jest Zwiastowanie, takie będzie i Zmartwychwstanie.',
'Gdy przed Zwiastowaniem ruszy się pszczoła, to mokrą wiosnę nam przywoła.',
'Mgła na Zwiastowanie znaczy rzek rozlanie.',
'Na Zwiastowanie, kiedy mgła w zaranie, chociaż słonko jasno wschodzi, znak niechybny to powodzi.',
'Na Zwiastowanie jaskółki się ukazują, ludziom wiosnę zwiastują.',
'Kto groch sieje w Wielki Wtorek, za garniec zbierze worek.',
'Wiosna panna, lato matka, jesień wdowa, zima macocha.',
'Marzec zielony ? niedobre plony.',
'Nieraz też zima i na końcu wiosny.',
'W Wielką Środę po kołaczach, gdy żaba zakuka, już nas zima mrozami pewnie nie oszuka.',
'Gdy w Ruperta niebo jasne będzie, w lipcu takiż czas pogody wszędzie.',
'Wiosną nadzieje rosną, przychodzi lato, czekamy na to, w jesieni może się zmienić, przychodzi zima znowu nic nie ma.',
'Gdy chcesz poznać pogodę w czerwcu roku tego, uważaj jak będzie w Jana Damasceńskiego.',
'I wiosna by tak nie smakowała, gdyby przedtem zimy nie było.',
'Nie jeden dzień ciepły czyni wiosnę po zimie',
'Gdy Wielki Piątek ponury, Wielkanoc będzie bez chmury.',
'Gdy w Wielki Piątek rosa, na łące nie chwyci się kosa.',
'Jeśli w Wielki Piątek deszcz kropi, radujcie się chłopi.',
'Jak w Wielki Piątek rosa, będzie obfity plon prosa.',
'We Wielki Piątek dobry zasiewu początek.',
'Jeśli w Wielki Piątek pada, suche lato zapowiada, ale gdy w ten dzień ładnie, dużo deszczów spadnie',
'Na wiosnę ceber deszczu - łyżka błota; na jesień łyżka deszczu - ceber błota.',
'Gdy się wieczór czerwienią nieba, w nocy albo jutro deszczu czekać trzeba.',
'Dobry bób kiedy głód; kiedy nie ma głodu, to się nie chce bobu.',
'Będzie pogoda, jak się nie poleje z nieba woda.',
'W marcu, gdy grzmot na lody spada, w lecie grad zapowiada.',
'Kiedy w marcu deszcze leją, nie ciesz się chłopie nadzieją.',
'Jak nie ma śniegu w marcu, deszczu w maju, to nie ma urodzaju.',
'Gdy marzec z deszczem chadza, mokry czerwiec sprowadza.',
'Źle się w marcu urodzić, bo trudno takiemu dogodzić'
];

przyslowia[4]=[
'Kwiecień plecień, bo przeplata trochę zimy, trochę lata',
];

przyslowia[5]=[
'W maju jak w gaju',
'Bywać śnieg i w maju',
];

przyslowia[0]=[
'Będzie pogoda, jak się nie poleje z nieba woda',
'Jedna jaskółka wiosny nie czyni',
'Na świętego Hieronima jest pogoda albo jej ni ma',
'Deszcze Michałowe prawią w zimie powietrze zdrowe',
'Gdy na święty Walek deszcze, mrozy wrócą jeszcze',
'Boże Narodzenie po wodzie, Wielkanoc po lodzie',
'Święta Barbara po wodzie, Boże Narodzenie po lodzie',
'Gdy na święty Walek deszcze, mrozy wrócą jeszcze',
'Boże Narodzenie po wodzie, Wielkanoc po lodzie',
'Święta Barbara po wodzie, Boże Narodzenie po lodzie',
];

